name: churn-imbalanced-dataset
on: [push]
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Changed to a specific version for better compatibility

      - name: Install CML
        uses: iterative/setup-cml@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          CXX: g++ # Ensures correct C++ compiler is used for sklearn and Cython compilation issues

      - name: Run ML Workflow Script
        run: |
          python script.py

      - name: Generate and Post Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Generate the report
          echo "## Metrics" > report.md
          
          # Append metrics to the report
          awk 'NR%4{print "    " $0}{print ""}' metrics.txt >> report.md

          # Append confusion matrix to the report
          echo "## Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md

          # Post the report as a comment
          cml comment create report.md