name: churn_prediction
on: [push]
permissions: write-all # required for CML to post comments
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Train model
        run: |
          source .venv/bin/activate
          python scripts.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Churn Prediction Report" > report.md
          cat metrics.txt >> report.md

          echo "\n## Model Performance" >> report.md
          if [ -f conf_matrix.png ]; then
            echo "![](./conf_matrix.png)" >> report.md
          else
            echo "Confusion matrix image is missing!" >> report.md
          fi

          cml comment create report.md