name: churn_mlops
on: [push]
permissions: write-all # required for CML to post comments
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: iterative/setup-cml@v1
      - name: prepare environment
        run: |
          # Your ML workflow goes here
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python script.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           # Generate a report with CML
            echo "# Churn ML Ops Report" > report.md
            awk '/^#/{print $0;getline;print}' metrics.txt >> report.md
            
            echo "## Confusion Matrix Visualization" >> report.md
            echo "![](./conf_matrix.png)" >> report.md
            
            # Add this line to post the report as a comment
            cml comment create report.md