name: churn_prediction
on: [push]
permissions: write-all # required for CML to post comments
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python scripts.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Churn Prediction Report" > report.md
          cat metrics.txt >> report.md

          echo "\n## Model Performance" >> report.md
          echo "![](./conf_matrix.png)" >> report.md

          # Post reports as comments in GitHub PRs
          cml comment create report.md